"""add cancellation_reason and is_cancelled to Order

Revision ID: 774adb979264
Revises: 7176fbf4c9ae
Create Date: 2025-04-23 18:32:03.215930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774adb979264'
down_revision = '7176fbf4c9ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancellation_reason', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_cancelled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('is_cancelled')
        batch_op.drop_column('cancellation_reason')

    # ### end Alembic commands ###
